version: "3.9"
services:
  db:
    image: postgres:11
    ports:
       - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=confluence
      - POSTGRES_DB=confluence
      - POSTGRES_PASSWORD=123456789
  confluence:
    image: atlassian/confluence-server@sha256:0ddf5e9d0a53f920d96bb45ba13529937f9285ab6e071503a498e40bf93a279b 
    # atlassian/confluence-server:7.10.1
    ports:
      - "127.0.0.1:8090:8090"
      - "127.0.0.1:8091:8091"
    depends_on:
      - db